---
- hosts: local
  become: yes
  tasks:
    - name: Install Docker
      pacman:
        name: docker
        state: present

    - name: Enable Docker
      systemd:
        name: docker
        enabled: yes
        state: started

    # Install kubectl
    - name: Install kubectl
      pacman:
        name: kubectl
        state: present

    # Install Minikube
    - name: Install Minikube
      pacman:
        name: minikube
        state: present

